//! Build script: bundle the `skills/` and `agents/` libraries into
//! the binary at compile time.
//!
//! Walks each directory and emits a generated Rust file under
//! `OUT_DIR` holding a `&[(name, relative_path, body)]` array, one
//! tuple per file. The arrays are `pub static`, so the embedded
//! content costs nothing at runtime beyond binary size. The
//! `roba skill` / `roba agent` subcommands read from these arrays
//! instead of fetching at runtime.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Re-run when the bundled content changes.
    println!("cargo::rerun-if-changed=skills");
    println!("cargo::rerun-if-changed=agents");
    println!("cargo::rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    emit_bundle(
        &manifest_dir.join("skills"),
        &out_dir.join("bundled_skills.rs"),
        "BUNDLED_SKILLS",
    );
    emit_bundle(
        &manifest_dir.join("agents"),
        &out_dir.join("bundled_agents.rs"),
        "BUNDLED_AGENTS",
    );
}

/// Walk `root`, collecting every file into a sorted list of
/// `(name, relative_path, absolute_path)` and emit a generated Rust
/// source file at `out_path` defining `static_name` as a
/// `&[(&str, &str, &str)]` of `(name, relative_path, body)`.
fn emit_bundle(root: &Path, out_path: &Path, static_name: &str) {
    let mut files: Vec<(String, String, PathBuf)> = Vec::new();
    if root.is_dir() {
        collect_files(root, root, &mut files);
    }
    files.sort_by(|a, b| a.1.cmp(&b.1));

    let mut body = String::new();
    body.push_str("// @generated by build.rs -- do not edit.\n");
    body.push_str(&format!(
        "pub static {static_name}: &[(&str, &str, &str)] = &[\n"
    ));
    for (name, rel, abs) in &files {
        // include_str! embeds the file content; the path is the
        // build-time absolute path so the macro resolves regardless
        // of OUT_DIR location.
        body.push_str(&format!(
            "    ({}, {}, include_str!({})),\n",
            quote(name),
            quote(rel),
            quote(&abs.to_string_lossy()),
        ));
    }
    body.push_str("];\n");

    fs::write(out_path, body).expect("writing generated bundle");
}

/// Recursively collect every file under `dir` into `out` as
/// `(top_level_dir_name, relative_path, absolute_path)`. The
/// `top_level_dir_name` is the first path component relative to
/// `root` (the skill/agent directory name); for files directly under
/// `root` (e.g. `README.md`) it is the file stem.
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<(String, String, PathBuf)>) {
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)
        .expect("reading bundle dir")
        .map(|e| e.expect("dir entry").path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            collect_files(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .expect("path under root")
                .to_string_lossy()
                .replace('\\', "/");
            // name = first path component (the skill/agent dir), or
            // the file stem when the file sits directly under root.
            let name = match rel.split_once('/') {
                Some((first, _)) => first.to_string(),
                None => Path::new(&rel)
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_else(|| rel.clone()),
            };
            out.push((name, rel, path));
        }
    }
}

/// Emit a Rust string literal for `s` using a raw-string form when
/// safe, falling back to an escaped literal. Bundled paths and names
/// never contain `"#`, so the simple raw form is always valid here,
/// but we escape defensively for the `body`-adjacent path strings.
fn quote(s: &str) -> String {
    if s.contains('"') || s.contains('\\') {
        let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
        format!("\"{escaped}\"")
    } else {
        format!("\"{s}\"")
    }
}
