//! Deterministic project initialization for the strict startup schema.

use std::io::Write;
use std::path::Path;

use anyhow::{Context, Result, bail};
use roba_core::PermissionPolicy;
use serde::Serialize;

use crate::cli::InitArgs;

const TARGET_NAME: &str = "roba.toml";
const PROJECT_CANDIDATES: [&str; 3] = ["roba.toml", ".roba.toml", ".roba/roba.toml"];
const HEADER: &str = "\
# Provider-neutral startup configuration for `roba run` and `roba serve`.
# Generated by `roba init`; edit this ordinary versioned file as needed.

";
const AMBIENT_GUIDANCE: &str = "
# This file does not select a managed agent role. Other discovered layers may
# still contribute one. Add `[context]` with catalog IDs when you want this
# project layer to select managed context.
";
const COMMON_GUIDANCE: &str = "
# Common next steps:
# - `[agent]` selects a provider, model, effort, and standing instructions.
# - `timeout_secs` under `[execution]` bounds each finite operation.
# - `[context]` selects managed agent, skill, and prompt catalog IDs.
# - `[extensions.git]` enables repository state and progress resources.
# Inspect all resolved layers and provenance with `roba config effective`.
# See the complete schema at:
# https://github.com/joshrotenberg/roba/blob/main/roba-startup.sample.toml
";

#[derive(Serialize)]
struct GeneratedStartupConfig {
    version: u32,
    execution: GeneratedExecutionConfig,
    #[serde(skip_serializing_if = "Option::is_none")]
    context: Option<GeneratedContextConfig>,
}

#[derive(Serialize)]
struct GeneratedExecutionConfig {
    permissions: PermissionPolicy,
}

#[derive(Serialize)]
struct GeneratedContextConfig {
    agent: String,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    skills: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    prompts: Vec<String>,
}

/// Create or preview one conservative project startup configuration.
pub fn run(args: InitArgs) -> Result<()> {
    let cwd = std::env::current_dir().context("resolving init workspace")?;
    let target = cwd.join(TARGET_NAME);
    let document = render(&args)?;
    if args.dry_run {
        crate::startup_config::validate_generated_document(&document, &target)
            .context("validating generated provider-neutral config")?;
        print!("{document}");
        return Ok(());
    }

    reject_existing_config(&cwd)?;
    crate::startup_config::validate_generated_install(&document, &target, &cwd)
        .context("validating generated provider-neutral config against discovered layers")?;
    install_noclobber(&target, &document)?;
    println!("Created {}", target.display());
    println!("Inspect: roba config effective");
    println!("Run: roba run \"inspect this repository\"");
    println!("Serve: mcp-repl -- roba serve");
    Ok(())
}

fn render(args: &InitArgs) -> Result<String> {
    let context = args
        .agent_role
        .as_ref()
        .map(|agent| GeneratedContextConfig {
            agent: agent.clone(),
            skills: args.skills.clone(),
            prompts: args.prompts.clone(),
        });
    let config = GeneratedStartupConfig {
        version: 1,
        execution: GeneratedExecutionConfig {
            permissions: PermissionPolicy::ReadOnly,
        },
        context,
    };
    let mut rendered = String::from(HEADER);
    rendered.push_str(&toml::to_string_pretty(&config)?);
    if args.agent_role.is_none() {
        rendered.push_str(AMBIENT_GUIDANCE);
    }
    rendered.push_str(COMMON_GUIDANCE);
    if !rendered.ends_with('\n') {
        rendered.push('\n');
    }
    Ok(rendered)
}

fn reject_existing_config(cwd: &Path) -> Result<()> {
    let existing = PROJECT_CANDIDATES
        .iter()
        .map(|candidate| cwd.join(candidate))
        .filter(|path| path.exists())
        .collect::<Vec<_>>();
    if existing.is_empty() {
        return Ok(());
    }
    let paths = existing
        .iter()
        .map(|path| path.display().to_string())
        .collect::<Vec<_>>()
        .join(", ");
    bail!(
        "refusing to initialize because this directory already contains a recognized Roba config: {paths}"
    )
}

fn install_noclobber(target: &Path, document: &str) -> Result<()> {
    let parent = target
        .parent()
        .ok_or_else(|| anyhow::anyhow!("init target has no parent: {}", target.display()))?;
    let mut temporary = tempfile::NamedTempFile::new_in(parent)
        .with_context(|| format!("creating temporary config in {}", parent.display()))?;
    temporary
        .write_all(document.as_bytes())
        .with_context(|| format!("writing temporary config for {}", target.display()))?;
    temporary
        .as_file_mut()
        .sync_all()
        .with_context(|| format!("syncing temporary config for {}", target.display()))?;
    temporary.persist_noclobber(target).map_err(|error| {
        anyhow::anyhow!(
            "installing provider-neutral config at {} without overwriting: {}",
            target.display(),
            error.error
        )
    })?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args() -> InitArgs {
        InitArgs {
            agent_role: None,
            skills: Vec::new(),
            prompts: Vec::new(),
            dry_run: false,
        }
    }

    #[test]
    fn default_document_is_minimal_ambient_and_read_only() {
        let document = render(&args()).unwrap();
        let value: toml::Value = toml::from_str(&document).unwrap();
        assert_eq!(value["version"].as_integer(), Some(1));
        assert_eq!(
            value["execution"]["permissions"].as_str(),
            Some("read_only")
        );
        assert!(value.get("agent").is_none());
        assert!(value.get("context").is_none());
        assert!(document.contains("does not select a managed agent role"));
    }

    #[test]
    fn managed_document_references_catalog_ids_without_copying_bodies() {
        let document = render(&InitArgs {
            agent_role: Some("roba.repo-worker".to_owned()),
            skills: vec!["roba.repository-change".to_owned()],
            prompts: vec!["roba.issue-worker".to_owned()],
            dry_run: false,
        })
        .unwrap();
        let value: toml::Value = toml::from_str(&document).unwrap();
        assert_eq!(value["context"]["agent"].as_str(), Some("roba.repo-worker"));
        assert_eq!(
            value["context"]["skills"][0].as_str(),
            Some("roba.repository-change")
        );
        assert_eq!(
            value["context"]["prompts"][0].as_str(),
            Some("roba.issue-worker")
        );
        assert!(!document.contains("bounded worker for one repository"));
    }

    #[test]
    fn no_clobber_install_preserves_existing_bytes() {
        let temp = tempfile::tempdir().unwrap();
        let target = temp.path().join(TARGET_NAME);
        std::fs::write(&target, "existing").unwrap();
        let error = install_noclobber(&target, "replacement").unwrap_err();
        assert!(error.to_string().contains("without overwriting"));
        assert_eq!(std::fs::read_to_string(target).unwrap(), "existing");
    }

    #[test]
    fn sibling_config_names_block_initialization() {
        for candidate in PROJECT_CANDIDATES {
            let temp = tempfile::tempdir().unwrap();
            let path = temp.path().join(candidate);
            std::fs::create_dir_all(path.parent().unwrap()).unwrap();
            std::fs::write(&path, "version = 1\n").unwrap();
            let error = reject_existing_config(temp.path()).unwrap_err();
            assert!(error.to_string().contains(&path.display().to_string()));
        }
    }
}
